import type { Metadata } from "next";
import { Poltawski_Nowy } from "next/font/google";
import "./globals.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/plugins.css";
import "../../public/assets/css/style.css";

import { CartProvider } from "../components/header/CartContext";
import { WishlistProvider } from "../components/header/WishlistContext";
import { ProductProvider } from "../components/context/page";
import { CategoryProvider } from "../components/context/CategoryContext"; // ✅ New Import

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const poltawskiNowy = Poltawski_Nowy({
  subsets: ["latin"],
  variable: "--font-poltawski-nowy",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Ekomart-Grocery-Store(e-Commerce) HTML Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/images/fav.png",
        type: "image/x-icon",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </head>
      <body className={`${poltawskiNowy.variable}`}>
          <WishlistProvider>
            <CartProvider>
              <ProductProvider>
                {/* ✅ Category Provider added here */}
                <CategoryProvider>
                  {children}
                  <ToastContainer position="top-right" autoClose={3000} />
                </CategoryProvider>
              </ProductProvider>
            </CartProvider>
          </WishlistProvider>
      </body>
    </html>
  );
}
